##### NumPy : Numerical Python
A library consisting of multidimensional array objects and a collection of routines for processing those arrays. 
Mathematical and logical operations on arrays can be performed. Also provides high performance.
Space efficient multi-dimensional array, which provides vectorized arithmetic operations. 

In [1]:
import numpy as np
import sys 
import time

In [2]:
print(np.__version__)

1.16.2


##### notice that --> python list taking 28000 bytes ,  numpy array taking 4000 bytes


In [3]:
l = range(1000)
print(sys.getsizeof(5)*len(l))      # getsizeof()  gives size of 1 element  pass any no.in it ()

array=np.arange(1000)
print(array.size * array.itemsize)    # array.itemsize  gives size of 1 element 

28000
4000


##### numpy array is fast and convenient , compared to python list

In [4]:
SIZE = 100000

l1 = range(SIZE)
l2 = range(SIZE)
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print('list time took : ', (time.time()-start)*1000)     # times in sec. , by *1000 change into -> milliseconds.


a1 = np.arange(SIZE)
a2 = np.arange(SIZE)
start = time.time()
result = a1 + a2
print('Numpy took time : ', (time.time()-start)*1000)    

list time took :  20.013809204101562
Numpy took time :  3.0019283294677734


In [5]:
a= np.array([1,2,3])                #  1-D
b= np.array([[1,2],[3,4],[5,6]])   # 2-D

print('ndim : gives dimension of matrix : ', a.ndim)             # ndim
print('ndim : gives dimension of matrix : ', b.ndim)

print('itemsize : gives size of 1 element : ', a.itemsize)       # itemsize : 

print('dtype : gives datatype : ', b.dtype)                      # dtype : 

print('size : gives size of total no. of elements : ', b.size)    # size

print('shape : gives (rows, columns) : ', b.shape)                # shape
b.shape=(2,3)    # we can change 'shape' of matrix
print(b)
b.reshape(3,2)   # we can again 'reshape' matrix
print(b)

ndim : gives dimension of matrix :  1
ndim : gives dimension of matrix :  2
itemsize : gives size of 1 element :  4
dtype : gives datatype :  int32
size : gives size of total no. of elements :  6
shape : gives (rows, columns) :  (3, 2)
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


##### ravel() , flatten()

In [6]:
c=np.array([[1,2],[3,4],[5,6]], dtype='int64')        # dtype=np.float64 , CHANGES dtype 4->8  , dtype=complex   
print(c)

print('\n ravel() create 1D all element in 1 row : ', c.ravel() , '\n')     # c.ravel()
print(c)     # after ravel() , it return original array

print('\n flatten() same does : ', c.flatten(), '\n')     # c.flatten() 
print(c)

[[1 2]
 [3 4]
 [5 6]]

 ravel() create 1D all element in 1 row :  [1 2 3 4 5 6] 

[[1 2]
 [3 4]
 [5 6]]

 flatten() same does :  [1 2 3 4 5 6] 

[[1 2]
 [3 4]
 [5 6]]


#### numpy.empty
It creates an uninitialized array of specified shape and dtype

In [7]:
import numpy as np 

x = np.empty([3,2], dtype = int) 
print(x)

[[1837725040         53]
 [         0          0]
 [         1       2044]]


##### sum()

In [8]:
print(c.sum(axis=0))        # aixs=0 : for column      and     axis=1 : for row

[ 9 12]


#### np.std() : standard deviation 

In [9]:
print(np.std(c))        

1.707825127659933


##### np.zeros() , np.ones()

In [10]:
np.zeros(5)                        # 1-D array matrix

array([0., 0., 0., 0., 0.])

In [11]:
print(np.zeros( (3,4) ) )    # ((3,4))  for 2D matrix ( () ) , intialize with zeros 0  , (3 rows 4 columns)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
print(np.ones((3,4)))     # ones 1          and 2-D matrix

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
print(np.zeros((3,4,4)))        # 3-D   , ( 3 matrix, 4 rows, 4 columns )  

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


#### np.full(), np.random.rand() , np.eye()

In [14]:
np.full((3,4),2)        # 3x4 array with all values of 2

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [15]:
np.random.rand(3,5)     # 3x5 array of random floats between 0-1

array([[0.47916932, 0.2833536 , 0.27096899, 0.49872924, 0.49889223],
       [0.88924122, 0.67355085, 0.02291865, 0.20607049, 0.13861087],
       [0.745377  , 0.93773548, 0.30953846, 0.60651057, 0.58319458]])

In [16]:
np.eye(4)       # 4x4 array of 0 with 1 on diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### numpy.asarray()
It is useful for converting Python sequence into ndarray.

In [17]:
x = [1,2,3]    # list
a = np.asarray(x, dtype = float) 
print(a)

x = (1,2,3)   # tuple
a = np.asarray(x)     # dtype=int
print(a)

[1. 2. 3.]
[1 2 3]


In [18]:
lists = range(5) 

# use iterator to create ndarray 
x = np.fromiter(lists, dtype = float)             # np.fromiter()
print(x)

[0. 1. 2. 3. 4.]


## -----------------

##### np.arange() , np.linspace() , np.logspace()

In [19]:
print(np.arange(2,10,2))         # 2-start , 10-stop (not included) , 2-steps

[2 4 6 8]


In [20]:
print(np.linspace(1,5,10))    # linear space , 10 no. generated b/w  1 and 5

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [21]:
# numpy.logspace(start, stop, num, endpoint, base, dtype)

a = np.logspace(1.0, 2.0, num = 10)             # default base is 10 
print(a)
print(20*'-')

a = np.logspace(1,10,num = 10, base = 2) 
print(a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
--------------------
[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


## ---------------------

#### Arithmetic operations such as : add(), subtract(), multiply(), and divide() 
##### dot() - used for multiplication 

In [22]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

print(np.add(x,y))         # print(x+y)       add()

print(np.subtract(x,y))    # print(x-y)       substract()

print(np.multiply(x,y))
# print(x*y)
# print(x.dot(y))      # dot() : for matrix multiplication

print(np.divide(x,y))
print(x/y)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


##### reciprocal() , power()

In [23]:
# A reciprocal is a pair of numbers (such as 5/6 and 6/5) that can be multiplied to produce 1.

a = np.array([0.25, 1.33, 1, 0, 100]) 
print(a)
print('reciprocal of a : ', np.reciprocal(a))  

[  0.25   1.33   1.     0.   100.  ]
reciprocal of a :  [4.        0.7518797 1.              inf 0.01     ]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in reciprocal
  """


In [24]:
a = np.array([10,100,1000]) 
print(np.power(a,2))               # np.power()

[    100   10000 1000000]


#### np.mod() , np.remainder()  
##### returns the remainder of division of the corresponding elements in the input array

In [25]:
a = np.array([10,20,30]) 
b = np.array([3,5,7])

print('mod : ', np.mod(a,b))
print('remainder : ', np.remainder(a,b))

mod :  [1 0 2]
remainder :  [1 0 2]


##### numpy.real() − returns the real part of the complex data type argument.
##### numpy.imag() − returns the imaginary part of the complex data type argument.
##### numpy.conj() − returns the complex conjugate, which is obtained by changing the sign of the imaginary part.
##### numpy.angle() − returns the angle of the complex argument. The function has degree parameter. If true, the angle in the degree is returned, otherwise the angle is in radians.

In [26]:
a = np.array([-5.6j, 0.2j, 11. , 1+1j]) 

print('real : ', np.real(a))     # real()

print('imaginary : ', np.imag(a))     # imag()

print('conjugate : ', np.conj(a))     # conj()

print('angle : ', np.angle(a))
print('angle in degree : ', np.angle(a, deg = True))   # in degrees

real :  [-0.  0. 11.  1.]
imaginary :  [-5.6  0.2  0.   1. ]
conjugate :  [-0.+5.6j  0.-0.2j 11.-0.j   1.-1.j ]
angle :  [-1.57079633  1.57079633  0.          0.78539816]
angle in degree :  [-90.  90.   0.  45.]


## --------------------------
#### Operations 

##### Copying

np.copy(array)    # Copies array to new memory array.

view(dtype)       # Creates view of array elements with type dtype

In [27]:
# Simple assignments do not make the copy of array object.
# When the contents are physically stored in another location, it is called Copy. 
# If on the other hand, a different view of the same memory content is provided, we call it as View.

a = np.arange(6) 
print(a)
print('id of a : ', id(a))    # Applying id() function 

b = a                         # a is assigned to b 
print(b)
print('id of b : ', id(b))    # same id


# If shape of 'b' changed then shape of 'a' also changed
b.shape = 3,2 

print('b : \n', b)
print('a : \n', a)

[0 1 2 3 4 5]
id of a :  229546881872
[0 1 2 3 4 5]
id of b :  229546881872
b : 
 [[0 1]
 [2 3]
 [4 5]]
a : 
 [[0 1]
 [2 3]
 [4 5]]


In [28]:
a = np.array([[10,10], [2,3], [4,5]]) 
print(a)

b = a.copy()         # Create copy of a
print(b)

# b does not share any memory of a 
print('True or False : ', b is a)

b[0,0] = 100     # Change the contents of b
print(b)
print(a)         # a remains unchanged

[[10 10]
 [ 2  3]
 [ 4  5]]
[[10 10]
 [ 2  3]
 [ 4  5]]
True or False :  False
[[100  10]
 [  2   3]
 [  4   5]]
[[10 10]
 [ 2  3]
 [ 4  5]]


In [29]:
a = np.arange(6).reshape(3,2) 
print('a: \n', a)

b = a.view()    # Create view of a 
print('b: \n', b)

print('a : ', id(a))                 # id for both the arrays are different
print('b : ', id(b))  

# Change the shape of b. It does not change the shape of a 
b.shape = 2,3 

print('shape of b : \n', b)
print('shape of a : \n', a)

a: 
 [[0 1]
 [2 3]
 [4 5]]
b: 
 [[0 1]
 [2 3]
 [4 5]]
a :  229546881312
b :  229546325936
shape of b : 
 [[0 1 2]
 [3 4 5]]
shape of a : 
 [[0 1]
 [2 3]
 [4 5]]


## ----------------------

### Sorting - 
#### np.sort() , np.argsort() , np.lexsort() , np.argmax(), np.argmin() , np.nonzero() , np.where() , np.extract()

In [30]:
a = np.array([[3,7],[9,1]])                                # np.sort()
print(a)
  
print(np.sort(a, axis = 0))

# Order parameter in sort function 
dt = np.dtype([('name', 'S10'),('age', int)]) 

a = np.array([("raju",21),("anil",25),("ravi", 17), ("amar",27)], dtype = dt)   # data type = dt
print(a)

print(np.sort(a, order = 'name'))    # Order by name

[[3 7]
 [9 1]]
[[3 1]
 [9 7]]
[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


In [31]:
x = np.array([3, 1, 2])                                          # np.argsort()
print(x)

y = np.argsort(x)        # Applying argsort() to x
print('y : \n', y)

print('\n', x[y])         # Reconstruct original array in sorted order

for i in y:
    print(x[i])          # Reconstruct the original array using loop

[3 1 2]
y : 
 [1 2 0]

 [1 2 3]
1
2
3


In [32]:
# function performs an indirect sort using a sequence of keys.                  # np.lexsort()

nm = ('raju','anil','ravi','amar') 
dv = ('f.y.', 's.y.', 's.y.', 'f.y.') 
ind = np.lexsort((dv,nm)) 

print(ind, '\n')        # Applying lexsort() function 

print([nm[i] + ", " + dv[i] for i in ind])       # Use this index to get sorted data

[3 1 0 2] 

['amar, f.y.', 'anil, s.y.', 'raju, f.y.', 'ravi, s.y.']


In [33]:
# These two functions return the indices of maximum and minimum elements respectively along the given axis.

a = np.array([[30,40,70],[80,20,10],[50,90,60]])                       # argmax()  &  argmin()
print(a)     

print(np.argmax(a))               
print(a.flatten())       # Index of maximum number in flattened array

maxindex = np.argmax(a, axis = 0)       # Array containing indices of maximum along,  axis=0, axis=1
print(maxindex)

# Applying argmin() function
minindex = np.argmin(a) 
print(minindex)

print(a.flatten()[minindex])       # flattened array

minindex = np.argmin(a, axis = 0)       # argmin()  , axis=0, axis=1
print(minindex)

[[30 40 70]
 [80 20 10]
 [50 90 60]]
7
[30 40 70 80 20 10 50 90 60]
[1 2 0]
5
10
[0 1 1]


In [34]:
# The numpy.nonzero() function returns the indices of non-zero elements in the input array.

a = np.array([[30,40,0],[0,20,10],[50,0,60]])                   # np.nonzero()
print(a)

print(np.nonzero(a))

[[30 40  0]
 [ 0 20 10]
 [50  0 60]]
(array([0, 0, 1, 1, 2, 2], dtype=int64), array([0, 1, 1, 2, 0, 2], dtype=int64))


In [35]:
# The where() function returns the indices of elements in an input array where the given condition is satisfied.

x = np.arange(9.).reshape(3, 3) 
print(x)

y = np.where(x > 3)         # Indices of elements > 3
print(y)

print(x[y])      # Use these indices to get elements satisfying the condition

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))
[4. 5. 6. 7. 8.]


In [36]:
# The extract() function returns the elements satisfying any condition.

x = np.arange(9.).reshape(3, 3) 
print(x)

# define a condition 
condition = np.mod(x,2) == 0 
print(condition)                     # Element-wise value of condition' 

print('extract: ', np.extract(condition, x))       # Extract elements using condition

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ True False  True]
 [False  True False]
 [ True False  True]]
extract:  [0. 2. 4. 6. 8.]


## -------------------

### Adding  
##### np.append()  ,  np.insert()

In [37]:
a = np.array([[1,2,3],[4,5,6]])                         # np.append()
print(a)

print(np.append(a, [7,8,9]))                       

print(np.append(a, [[7,8,9]], axis = 0))         # axis=0

print(np.append(a, [[5,5,5],[7,8,9]], axis = 1))    # axis=1 

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [38]:
a = np.array([[1,2],[3,4],[5,6]])                            # np.insert()
print(a)

print(np.insert(a,3,[11,12]))  # Axis parameter not passed. The input array is flattened before insertion

print(np.insert(a,1,[11], axis=0))  # Axis parameter passed. The values array is broadcast to match input array 

print(np.insert(a,1,11, axis=1))

[[1 2]
 [3 4]
 [5 6]]
[ 1  2  3 11 12  4  5  6]
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


#### broadcasting

In [39]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0]) 

print(a+b)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


## ----------------------

### Removing
##### np.delete()

In [40]:
a = np.arange(12).reshape(3,4) 
print(a)

print(np.delete(a,5))   # Array flattened before delete operation as axis not used

print(np.delete(a,1,axis = 1))    # Column 2 deleted

# A slice containing alternate values from array deleted
a = np.array([1,2,3,4,5,6,7,8,9,10]) 
print(np.delete(a, np.s_[::2]))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  6  7  8  9 10 11]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]
[ 2  4  6  8 10]


## ------------------

### slicing

In [41]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])                                 # slicing

print(a[1,2])    # start from 0 indexing
print(a[:, 2])   # allrows, 2nd column
print(a[-1])     # gives last row
print(a[:,1:3])  # takes all rows , then 1st 2nd columns  not 0th-column

6
[3 6 9]
[7 8 9]
[[2 3]
 [5 6]
 [8 9]]


## ----------------------

#### Combining
##### np.concatenate() , np.stack() , np.hstack() , np.vstcack()

In [42]:
a = np.array([[1,2],[3,4]]) 
# print(a)

b = np.array([[5,6],[7,8]]) 
# print(b)

# both the arrays are of same dimensions, Joining the two arrays along, axis=0
print(np.concatenate((a,b)))                # axis=0

print(np.concatenate((a,b),axis = 1))        # axis=1

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [43]:
a = np.array([[1,2],[3,4]])                      # np.stack()
# print(a)
b = np.array([[5,6],[7,8]]) 
# print(b)

print(np.stack((a,b),0))     # Stack the two arrays along, axis=0

# print(np.stack((a,b),1))       # Stack the two arrays along, axis=1

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [44]:
x = np.arange(6).reshape(3,2)                            # stacking  , np.hstack(), np.vstack()
y = np.arange(6,12).reshape(3,2)

print('v stack : \n', np.vstack((x,y)))    # stacks vertically all x, y array
print('h stack : \n', np.hstack((x,y)))    # stacks horizontally

v stack : 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
h stack : 
 [[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


### Split
##### np.split(), np.hsplit(), np.vsplit()

In [45]:
a = np.arange(9) 
# print(a)
b = np.split(a,3)                     # split
print(b)
print(20*'-','\n')


s = np.arange(30).reshape(3,10)                
print(s)
print('\n', np.hsplit(s,2))              # hsplit : splits basically into vertical

horizontal = np.hsplit(s,2)              # use this way
# print('h0 : \n', horizontal[0])
# print('h1 : \n', horizontal[1])

print(np.vsplit(s,3))                  # vsplit : splits basically into horizontal

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
-------------------- 

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]

 [array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]]), array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])]
[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]), array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]


#### indexing

In [46]:
r = np.arange(12).reshape(3,4)                           
print(r)

q=r>4    # checks r elements > 4  and
print(q)  # gives boolean

print(r[q])   # return True values

r[q]=-1    # Here we assign -1 to True values , return array
print(r)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]


## ---------------------------------

## nditer()

###### flat

In [47]:
a = np.arange(12).reshape(3,4)                                   # iterate using nditer()

print(a)

for row in a:       # for loop
    print(row)

for cell in a.flat:               # flat : converts into  1-D
    print(cell, end=' ')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
0 1 2 3 4 5 6 7 8 9 10 11 

In [48]:
for x in np.nditer(a, order='C'):              # order='C' : prints row-wise    , oreder='F' : prints column-wise 
    print(x, end=' ')
    
    
for x in np.nditer(a, order='F', flags=['external_loop']):      # order='C' in single row ,  order='F' in columns
    print('\n',x)
    
    
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x                                  # it will suare all elements of array
print(a)                  # and modify the array

0 1 2 3 4 5 6 7 8 9 10 11 
 [0 4 8]

 [1 5 9]

 [ 2  6 10]

 [ 3  7 11]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [49]:
# iterate from two arrays ->  a , b
b=np.arange(3,15,4).reshape(3,1)    
print(b)

for x,y in np.nditer([a,b]):     # iterate a,b and takes 1st row of both array a,b
    print(x,y)                   # then so on

[[ 3]
 [ 7]
 [11]]
0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


In [50]:
my_vector = np.array([7,14,65,45,25,31,89,47,-21])             # checking divisible  by 7 , modulus %

zero_mode_7_mask = 0 ==(my_vector%7)                 # use this or 
print(zero_mode_7_mask)

zero_mode = np.where(my_vector%7==0,True,False)     # this  
print(zero_mode)

[ True  True False False False False False False  True]
[ True  True False False False False False False  True]


In [51]:
sub_array = my_vector[zero_mode_7_mask]     # assigning True values in ->sub_array
print(sub_array)

print( sub_array[sub_array > 0] )         # sub_array as mask-array to index itself , give True values

[  7  14 -21]
[ 7 14]


In [52]:
# Numpy logical Operators   ,  another method -> of masking

mod_test = 0 ==(my_vector%7)
positive_test = my_vector > 0

combine_mask = np.logical_and(mod_test,positive_test)
print(combine_mask)

[ True  True False False False False False False False]


In [53]:
my_3D_array = np.arange(70)
my_3D_array.shape = (2,7,5)

print(5 * my_3D_array - 2)

[[[ -2   3   8  13  18]
  [ 23  28  33  38  43]
  [ 48  53  58  63  68]
  [ 73  78  83  88  93]
  [ 98 103 108 113 118]
  [123 128 133 138 143]
  [148 153 158 163 168]]

 [[173 178 183 188 193]
  [198 203 208 213 218]
  [223 228 233 238 243]
  [248 253 258 263 268]
  [273 278 283 288 293]
  [298 303 308 313 318]
  [323 328 333 338 343]]]


In [54]:
print(my_3D_array)
print(my_3D_array.sum(axis=0))
print(my_3D_array.sum(axis=1))
print(my_3D_array.sum(axis=2))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]]

 [[35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]
[[ 35  37  39  41  43]
 [ 45  47  49  51  53]
 [ 55  57  59  61  63]
 [ 65  67  69  71  73]
 [ 75  77  79  81  83]
 [ 85  87  89  91  93]
 [ 95  97  99 101 103]]
[[105 112 119 126 133]
 [350 357 364 371 378]]
[[ 10  35  60  85 110 135 160]
 [185 210 235 260 285 310 335]]


In [55]:
my_2D_array = np.ones(35, dtype='int').reshape(7,5)*3         # changes all ones 1 into 3
my_2D_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [56]:
my_random_2D_array = np.random.random((7,5))
np.set_printoptions(precision=4)              # precision=4 ,gives 4 decimal digits in float
print(my_3D_array * my_random_2D_array)

[[[ 0.      0.6347  0.7097  2.7448  3.9821]
  [ 4.6068  3.6442  1.8483  0.3743  6.8461]
  [ 2.1172  2.9498 10.657   1.4463  0.5581]
  [ 2.2825  6.5437 12.464  12.3732  5.6308]
  [12.76    9.3658  8.2843 10.4262  5.8817]
  [11.4241 18.9731  2.9822 14.8963 21.951 ]
  [29.8702  8.2016 26.7015 11.6003  3.4917]]

 [[26.7309 22.8489 13.1293 34.7673 38.8251]
  [36.8547 24.9021 11.0899  2.0121 33.4699]
  [ 9.5274 12.3356 41.74    5.3402  1.9533]
  [ 7.6082 20.8579 38.1251 36.4322 16.0033]
  [35.0901 24.9756 21.4639 26.2921 14.4592]
  [27.4178 44.5137  6.8479 33.5167 48.4436]
  [64.7188 17.4616 55.9063 23.9037  7.086 ]]]


In [57]:
my_vector = np.arange(5)*7
my_vector[0] = -1
my_vector

array([-1,  7, 14, 21, 28])

#### exec() function


In [58]:
code=input("enter what you want to do : ")     # enter ->  [print(x**2) for x in range(7)]
exec(code)

enter what you want to do : 5+2


In [59]:
import os  

# by importing os , we can find all files and deletes through exec() , its dangerous also  
# ny entering --> print(os.listdir())

In [60]:
person_data_def = [('name','S6'),('height','<f8'),('weight','<f8'),('age','<i8')]
print(person_data_def)

people_array = np.zeros((4), dtype=person_data_def)
print(people_array)    # b -> indicate it is a string

people_array[3] = ('delta',73,205,34)
people_array[0] = ('alpha',65,112,23)
print(people_array)

[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')]
[(b'', 0., 0., 0) (b'', 0., 0., 0) (b'', 0., 0., 0) (b'', 0., 0., 0)]
[(b'alpha', 65., 112., 23) (b'',  0.,   0.,  0) (b'',  0.,   0.,  0)
 (b'delta', 73., 205., 34)]


#### structured multidimensional arrays


In [61]:
people_big_array = np.zeros((4,3,2),dtype=person_data_def)
print(people_big_array)

people_big_array[3,2,1] = ('echo',68,105,46)
print(people_big_array)

print(people_big_array['height'])
print(people_big_array[['height','weight']])

[[[(b'', 0., 0., 0) (b'', 0., 0., 0)]
  [(b'', 0., 0., 0) (b'', 0., 0., 0)]
  [(b'', 0., 0., 0) (b'', 0., 0., 0)]]

 [[(b'', 0., 0., 0) (b'', 0., 0., 0)]
  [(b'', 0., 0., 0) (b'', 0., 0., 0)]
  [(b'', 0., 0., 0) (b'', 0., 0., 0)]]

 [[(b'', 0., 0., 0) (b'', 0., 0., 0)]
  [(b'', 0., 0., 0) (b'', 0., 0., 0)]
  [(b'', 0., 0., 0) (b'', 0., 0., 0)]]

 [[(b'', 0., 0., 0) (b'', 0., 0., 0)]
  [(b'', 0., 0., 0) (b'', 0., 0., 0)]
  [(b'', 0., 0., 0) (b'', 0., 0., 0)]]]
[[[(b'',  0.,   0.,  0) (b'',  0.,   0.,  0)]
  [(b'',  0.,   0.,  0) (b'',  0.,   0.,  0)]
  [(b'',  0.,   0.,  0) (b'',  0.,   0.,  0)]]

 [[(b'',  0.,   0.,  0) (b'',  0.,   0.,  0)]
  [(b'',  0.,   0.,  0) (b'',  0.,   0.,  0)]
  [(b'',  0.,   0.,  0) (b'',  0.,   0.,  0)]]

 [[(b'',  0.,   0.,  0) (b'',  0.,   0.,  0)]
  [(b'',  0.,   0.,  0) (b'',  0.,   0.,  0)]
  [(b'',  0.,   0.,  0) (b'',  0.,   0.,  0)]]

 [[(b'',  0.,   0.,  0) (b'',  0.,   0.,  0)]
  [(b'',  0.,   0.,  0) (b'',  0.,   0.,  0)]
  [(b'',  0.,   0.,  0) 

#### Record arrays


In [62]:
person_record_array = np.rec.array([('Delta',73,205,34),('Alpha',65,112,23)],dtype=person_data_def)
print(person_record_array)
print(person_record_array[0].age)

[(b'Delta', 73., 205., 34) (b'Alpha', 65., 112., 23)]
34


## -----------------------------

### saving  and  loading 

np.save()  ,  np.load()

In [63]:
a = np.arange(5) 
print("a is:", a)                      # np.save()

np.save('geekfile', a)    # the array is saved in the file ' geekfile.npy '

a is: [0 1 2 3 4]


In [64]:
b = np.load('geekfile.npy') 

print("b is:", b)                     # np.load()

b is: [0 1 2 3 4]


#### Text/CSV files:

np.loadtxt('New_file.txt')                       # from a text file

np.genfromtxt('New_file.csv',delimiter=',')      # from a CSV file

np.savetxt('New_file.txt',arr,delimiter=' ')     # writes to a text file

np.savetxt('New_file.csv',arr,delimiter=',')     # writes to a CSV file